name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 12 * * *"}]
  # Lines below let you run workflow manually and on each commit (optional)
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # See action.yml for all options
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
       # ... other options
          plugin_introduction: yes
          plugin_introduction_title: no # Hide section title
       # ... other options
          plugin_languages: yes
          plugin_languages_skipped: profile                        # List of repositories to skip
          plugin_languages_aliases: "JavaScript:JS, TypeScript:TS, ..." # Customize languages names with aliases
          plugin_languages_details: bytes-size, percentage              # Additionally display total bytes size and percentage
          plugin_la nguages_threshold: 2%                               # Hides all languages less than 2%
          plugin_languages_limit: 8                                     # Display up to 8 languages
          commits_authoring: Minh T Bui    
       
          
